---

- name: "MY FIRST PLAYBOOK"
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "OSPF config"
      cisco.ios.ios_banner:
        banner: motd
        text: |
          #######################################
          #### ACCESS PROHIBITED TO ONLY EZE ####
          #######################################          
        state: present

      register: my_output

    - debug: var=my_output
